---
title: "Cartas de naturaleza"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = FALSE)
```


```{r setup_BOE}
suppressPackageStartupMessages(library("data.table", warn.conflicts = FALSE))
library("dtplyr", warn.conflicts = FALSE)
library("dplyr", warn.conflicts = FALSE)
library("lubridate", warn.conflicts = FALSE)
suppressPackageStartupMessages(library("ggplot2", warn.conflicts = FALSE))
library("gghighlight", warn.conflicts = FALSE)
library("forcats", warn.conflicts = FALSE)
library("stringr", warn.conflicts = FALSE)


con <- DBI::dbConnect(RSQLite::SQLite(),
                      dbname = "sumarios.sqlite")
dff <- con %>% 
    tbl("sumario") %>% 
    collect() %>% 
    mutate(date = as.Date(date),
           weekday = weekdays(date))
DBI::dbDisconnect(con)
```


```{r buscando}
cn2 <- dff %>% 
    filter(epigraph == "Nacionalidad española") %>% 
    as_tibble()
cn <- cn2 %>% 
    mutate(CN = str_detect(text, "carta de naturaleza"))
```

Esta vez repito un poco el análisis de [Cívio](https://civio.es/el-boe-nuestro-de-cada-dia/2013/06/24/espanoles-por-decreto/), pero sólo a partir de 2009 y hasta 2019. Más que nada para confirmar que las cifras cuadren, que efectivamente se da.

```{r dates}
cn %>% 
    count(date) %>% 
    ggplot(aes(date, n)) + 
    geom_col() +
    scale_x_date(labels = scales::date_format("%Y"), date_breaks = "1 year") +
    scale_y_continuous(expand = c(0, 1)) +
    labs(x = element_blank(), y = "Cartas de naturaleza",
         caption = "Fuente: Agencia Estatal del Boletín Oficial del Estado") +
    theme_bw()
```

```{r years}
cn %>% 
    count(Year = format(date, "%Y")) %>%
    mutate(Cartas = "Yes") %>% 
    ggplot() + 
    geom_col(aes(Year, n)) +
    scale_y_continuous(expand = c(0, 10)) +
    labs(x = element_blank(), y = "Cartas de naturaleza",
         caption = "Fuente: Agencia Estatal del Boletín Oficial del Estado") +
    theme_bw() +
    theme(panel.grid.major.x = element_blank())
    
cn %>% 
    count(Year = format(date, "%Y")) %>%
    knitr::kable(row.names = FALSE, align = "c")
```

Para terminar con un poquito más de contenido. Los otros epígrafes sobre la "Nacionalidad española" que no son sobre cartas de naturaleza:


```{r kable, }
d <- cn %>% 
    filter(!CN) %>% 
    select(date, section, section_number, departament, text, publication)

knitr::kable(d, format = "html", row.names = TRUE, align = "c", 
             col.names = c("Fecha", "Sección", "Texto sección", "Departamento", 
                       "Texto publicación", "Publicación"))
```

