---
title: "Lo último del BORME"
description: "Resumen de lo publicado hoy en el BORME."
base_url: https:llrs.github.io/BOE_historico/
repository_url: https://github.com/llrs/BOE_historico
output:
  html_document:
    includes:
      in_header: twitter_BORME.html
output_dir: docs
self_contained: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message=FALSE, warning=FALSE, error=FALSE)
```

```{r dates}
today <- Sys.Date()
library("BOE")
sumario_hoy <- try(retrieve_sumario(today, journal = "BORME"), silent = TRUE)
if (is(sumario_hoy, "try-error")) {
    knitr::knit_exit()
}
```

# Resumen gráfico

Esta página web contiene el último sumario del BORME publicado el `r today` con `r nrow(sumario_hoy)` publicaciones.

```{r graphics, fig.asp="center"}
library("dplyr")
library("forcats")
library("ggalluvial")
sumario_hoy %>% 
    group_by(section_number, emisor) %>% 
    count(name = "Freq", sort = TRUE) %>% 
    ungroup() %>% 
    mutate(section_number = gsub("SECCIÓN .*\\. ", "", section_number),
           emisor = tolower(emisor)) %>% 
    arrange(section_number, emisor, Freq) %>% 
    mutate(emisor = as.factor(emisor),
           section_number = as.factor(section_number),
           emisor = fct_inorder(emisor),
           section_number = fct_inorder(section_number)) %>% 
    ggplot(aes(y = Freq, 
               axis1 = forcats::fct_reorder(section_number, -Freq, sum), 
               axis2 = forcats::fct_reorder(emisor, -Freq, sum))) +
    geom_alluvium(aes(fill = as.factor(emisor))) +
    geom_stratum(fill = "white", color = "darkgrey") +
    # geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
    ggfittext::geom_fit_text(mapping = aes(label = after_stat(stratum)), 
                           stat = "stratum", min.size = 1) +
    guides(fill = "none") +
    scale_x_discrete(limits = c("section_number", "emisor")) +
    theme_void() +
    labs(title = paste0("Anuncios del BORME publicados el ", today),
         caption = "Fuente: Agencia Estatal del Boletín Oficial del Estado\nAutor: @Lluis_Revilla")
ggsave("docs/last_BORME_files/figure-html/graphics-1.png")
```

# Tabla de publicaciones

Aquí está la tabla completa con enlaces a las publicaciones:

```{r report, echo = FALSE, layout="l-body-outset"}
pubs <- url_publications(sumario_hoy)
pubs <- paste0("<a href=", pubs, ">", sumario_hoy$publication, "</a>")
s <- cbind(sumario_hoy, pubs)
s <- s[, c(5, 6, 8, 10)]
colnames(s) <- c("Sección", "Emisor", "Texto", "Link")
DT::datatable(s, filter = 'top', options = list(
  pageLength = 10, autoWidth = TRUE
), escape = FALSE)

```

```{r twitter, eval=as.logical(Sys.getenv("BOE_TWITTER"))}
library("rtweet")

media_alt_txt <- paste("Gráfico alluvial con el BORME publicado hoy.",
                       "Hay dos columnas de las categorías sección y emisor, ordenado por frequencia.")
files2 <- "docs/last_BORME_files/figure-html/graphics-1.png"
status <- "Resumen del #BORME de hoy en: https://llrs.github.io/BOE_historico/last_BORME.html"
r <- post_tweet(status = paste0(status, collapse = ""),
           media = files2, media_alt_text = media_alt_txt)
```

