---
title: "Lo último del BOE"
description: "Resumen de lo publicado hoy en el BOE."
base_url: https:llrs.github.io/BOE_historico/
repository_url: https://github.com/llrs/BOE_historico
preview: boe-01.png
twitterImg: boe-01.png
output_dir: docs
self_contained: false
template:
  opengraph:
    image:
      src: boe-01.png
      alt: "Resumen en formato tabla del último sumario del BOE."
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, layout = "l-body-outset", 
                      message = FALSE, warning = FALSE, error = FALSE)
```


```{r dates, include=FALSE}
today <- Sys.Date()
yesterday <- today -1
library("BOE")
sumario_hoy <- try(retrieve_sumario(today), silent = TRUE)
d <- today
if (is(sumario_hoy, "try-error")) {
    d <- yesterday
   sumario_hoy <- retrieve_sumario(yesterday)
}
ts <- table(gsub(pattern = "BOE-([AB])-.*", replacement = "\\1", sumario_hoy$publication))
```

# Resumen grafico

Esta página web contine el último sumario del BOE publicado el `r d` con `r nrow(sumario_hoy)` publicaciones, de las cuales `r ts[["A"]]` son disposiciones.

```{r graphics, layout="l-body-outset"}
library("dplyr")
library("ggalluvial")
library("forcats")
library("patchwork")
freqs <- sumario_hoy %>% 
  mutate(Type = ifelse(is.na(epigraph), "Anuncio", "Disposición")) %>% 
  group_by(section_number, departament, Type, epigraph) %>% 
  count(name = "Freq", sort = TRUE) %>% 
  ungroup() %>% 
  arrange(section_number, departament) %>% 
  mutate(section = fct_inorder(as.factor(section_number)),
         departament = fct_inorder(as.factor(tolower(departament))),
         epigraph = fct_inorder(as.factor(epigraph))) %>% 
  mutate(section = gsub(" - ", "\n", section))
p1 <- freqs %>% 
    filter(Type == "Anuncio") %>% 
    ggplot(aes(y = Freq, 
               axis1 = forcats::fct_reorder(section, -Freq, .fun = sum), 
               axis2 = forcats::fct_reorder(departament, -Freq, .fun = sum))) +
    geom_alluvium() +
    geom_stratum(fill = "white", color = "darkgrey") +
    geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
    guides(fill = FALSE) +
    theme_void() +
labs(title = paste("Anuncios publicadas el", today),
         caption = "Fuente: Agencia Estatal del Boletín Oficial del Estado\nAutor: @Lluis_Rev")
p2 <- freqs %>% 
    filter(Type != "Anuncio") %>% 
    ggplot(aes(y = Freq, 
               axis1 = forcats::fct_reorder(section, -Freq, .fun = sum), 
               axis2 = forcats::fct_reorder(departament, -Freq, .fun = sum), 
               axis3 = forcats::fct_reorder(epigraph, -Freq, .fun = sum))) +
    geom_alluvium(fill = "grey") +
    geom_stratum(fill = "white", color = "darkgrey") +
    geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
    guides(fill = FALSE) +
    theme_void() +
    labs(title = paste("Disposiciones publicadas el", today),
         caption = "Fuente: Agencia Estatal del Boletín Oficial del Estado\nAutor: @Lluis_Rev")
p2
```

# Tabla

Aquí está la tabla completa con links:

```{r report, layout="l-body-outset"}
pubs <- url_publications(sumario_hoy)
pubs <- paste0("<a href=", pubs, ">", sumario_hoy$publication, "</a>")
s <- cbind(sumario_hoy, pubs)
s <- s[, -c(1, 2, 3, 4, 7, 10)]
colnames(s) <- c("Sección", "Departamento", "Epígrafe", "Texto", "Páginas", "Link")
DT::datatable(s, filter = 'top', options = list(
  pageLength = 10, autoWidth = TRUE
), escape = FALSE)
```

```{r anuncios, layout="l-body-outset"}
p1
```

```{r twitter}
library("rtweet")
nacionalizaciones <- sum(grepl(x = sumario_hoy$text, 
            pattern = "concede la nacionalidad española"))
extravios <- sum(grepl(x = sumario_hoy$text, 
                               pattern = "extrav[íi]o del? (un )?t[íi]tulo"))
medallas <- sum(sumario_hoy$epigraph == "Condecoraciones", na.rm = TRUE)
subvenciones <- sum(sumario_hoy$epigraph == "Subvenciones", na.rm = TRUE)
disposiciones <- ts[["A"]]
anuncios <- ts[["B"]]
anuncios_particulares <- sum(sumario_hoy$section == "5C", na.rm = TRUE)
link0 <- "https://llrs.github.io/BOE_historico/last_BOE.html"
links <- c("Lo podeis consultar fácilmente en ", 
           "Mirad el resumen de lo publicado hoy en ",
           "Todo lo publicado en ")
link <- paste0(sample(links, 1), link0)
status <- paste("Hoy hay", disposiciones, "disoposiciones y",
                anuncios, "anuncios nuevos en el #BOE.\n")
if (extravios > 0) {
  status <- c(status, "De ellos ", extravios, 
         " extravíos de títulos universitarios.\n")
}
if (nacionalizaciones > 0) {
  status <- c(status, "También", nacionalizaciones, 
         " cartas de naturaleza.\n")
}
if (medallas > 0) {
  status <- c(status, "Otorgadas", medallas, 
         " condecoraciones.\n")
}
if (subenciones > 0) {
  status <- c(status, "Otorgadas", medallas, 
         " subvenciones.\n")
}
if (anuncios_particulares > 0) {
  status <- c(status, "Importante: ", anuncios_particulares, 
         " anuncios particulares.\n")
}

status <- c(status, link)

if (sum(nchar(status)) > 280) {
  status <- paste0("Hoy el #BOE va muy cargado...\n.", link)
}

id_tweet <- function(x) {
  httr::content(x)$id_str
}

r <- post_tweet(status = paste0(status),
           media = "docs/last_BOE_files/figure-html/graphics-1.png")
# r2 <- post_tweet(status, in_reply_to_status_id = id_tweet(r), 
#            auto_populate_reply_metadata = TRUE)
```
